// GoGoJap Chinese → English Translation Script v2
// Strategy: Process line-by-line, only translate Chinese segments within comments and string literals
// NEVER do single-character translations - only full phrase/word matches

import { readFileSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';

const srcDir = '.';

// Get all files with Chinese
const rawOutput = execSync(
  `powershell -Command "Get-ChildItem -Recurse -Include *.tsx,*.ts,*.jsx | Select-String -Pattern '[\\u4e00-\\u9fff]' | Select-Object -ExpandProperty Path -Unique"`,
  { cwd: srcDir, encoding: 'utf-8' }
);
const files = rawOutput.trim().split('\n')
  .map(f => f.trim())
  .filter(f => f && (f.endsWith('.tsx') || f.endsWith('.ts') || f.endsWith('.jsx')));

console.log(`Found ${files.length} files with Chinese text\n`);

// COMPREHENSIVE translation dictionary
// Sorted longest-first to prevent partial matches
// IMPORTANT: No single-character entries! Minimum 2 characters.
const translations = [
  // ==================== LONG PHRASES (10+ chars) ====================
  ['選中的任務（用於批量刪除）', 'Selected tasks (for batch deletion)'],
  ['風格描述（專業攝影模式才顯示）', 'Style description (shown only for professional photo mode)'],
  ['如果任務還在處理中，繼續輪詢', 'If task is still processing, continue polling'],
  ['當任務數據加載後，獲取輸入圖片的預簽名', 'After task data loads, fetch presigned URLs for input images'],
  ['獲取輸入圖片的預簽名', 'Fetch presigned URLs for input images'],
  ['選中/取消選中單個任務', 'Select / Deselect individual task'],
  ['全選/取消全選', 'Select all / Deselect all'],
  ['根據角色計算限制', 'Calculate limits based on role'],
  ['跳轉到結果頁面', 'Redirect to results page'],
  ['忽略自動播放限制錯誤', 'Ignore autoplay restriction error'],
  ['從 localStorage 讀取', 'Read from localStorage'],
  ['圖片生成歷史記錄頁面', 'Image Generation History Page'],
  ['圖片生成結果頁面', 'Image Generation Results Page'],
  ['圖片生成上傳頁面', 'Image Generation Upload Page'],
  ['圖片信息和分析結果', 'Image info and analysis results'],
  ['輸入圖片和 AI 分析結果', 'Input images and AI analysis results'],
  ['每張圖片輸出數量', 'Outputs per image'],
  ['每 2 秒輪詢一次', 'Poll every 2 seconds'],
  ['全息賽博朋克導航欄示範頁面', 'Holographic cyberpunk navigation bar demo page'],
  ['從舊的 localStorage 遷移 token 到新的安全存儲', 'Migrate token from old localStorage to new secure storage'],
  ['同時清除舊的 localStorage token（遷移用）', 'Also clear old localStorage token (migration)'],
  ['使用安全 Token 管理器（sessionStorage + 內存緩存）', 'Use secure token manager (sessionStorage + memory cache)'],
  ['使用 sessionStorage + 內存緩存，防止 XSS 攻擊', 'Use sessionStorage + memory cache to prevent XSS attacks'],
  ['安全獲取 API Key（僅在需要時從環境變量讀取，不緩存）', 'Securely fetch API Key (read from env vars only when needed, no caching)'],
  ['防止 SSRF 攻擊，確保只爬取允許的域名', 'Prevent SSRF attacks, ensure only allowed domains are scraped'],
  ['禁止訪問的內部網路範圍（防止 SSRF）', 'Block access to internal network ranges (prevent SSRF)'],
  ['使用自定義文件驗證器（只檢查副檔名，不檢查大小，因為會自動壓縮）', 'Use custom file validator (check extension only, not size, since auto-compression)'],
  ['使用 API Key 的前 8 字符作為用戶標識', 'Use first 8 chars of API Key as user identifier'],
  ['簡單的混淆函數（不是加密，僅增加攻擊難度）', 'Simple obfuscation function (not encryption, just adds attack difficulty)'],
  ['存儲到 sessionStorage（混淆後）', 'Store to sessionStorage (obfuscated)'],
  ['嘗試從 sessionStorage 讀取', 'Try to read from sessionStorage'],
  ['優先從內存讀取（最安全）', 'Prefer reading from memory (most secure)'],
  ['如果 token 已過期或即將過期（少於 1 分鐘），不存儲', 'If token is expired or expiring soon (<1 min), do not store'],
  ['設置 Token 並自動從 JWT 提取過期時間', 'Set token and auto-extract expiry time from JWT'],
  ['無法提取過期時間，使用默認', 'Cannot extract expiry time, use default'],
  ['從 JWT 中提取過期時間', 'Extract expiry time from JWT'],
  ['從環境變量讀取，支持多 API Key（用逗號分隔）', 'Read from env vars, support multiple API Keys (comma-separated)'],
  ['檢查 Firecrawl 必需的 API Key（從環境變量）', 'Check required Firecrawl API Key (from env vars)'],
  ['驗證通過，返回清理後的', 'Validation passed, return cleaned'],
  ['每次調用時從環境變量讀取，避免內存中存儲敏感信息', 'Read from env vars on each call, avoid storing sensitive info in memory'],
  ['使用原始 axios 實例以獲取完整響應，繞過響應攔截器', 'Use raw axios instance for full response, bypass response interceptor'],
  ['響應攔截器：統一處理錯誤與數據格式', 'Response interceptor: unified error handling and data formatting'],
  ['後端可能返回 200 但 success: false，需要手動處理', 'Backend may return 200 with success: false, need manual handling'],
  ['配額即將用盡，請升級計劃以繼續使用。', 'Quota nearly exhausted, please upgrade your plan to continue.'],
  ['配額偏低，建議使用智能爬取以節省消耗。', 'Quota is low, consider using smart scraping to save usage.'],
  ['未配置 SCRAPER_API_KEYS 環境變量。', 'SCRAPER_API_KEYS environment variable is not configured.'],
  ['缺少 API Key（請在 header 中提供 x-api-key 或', 'Missing API Key (please provide x-api-key in header or'],
  ['這裡拆成多個依序請求，後端 upload_order 自動接續。', 'Split into sequential requests, backend upload_order auto-continues.'],
  ['頁面載入時發生未知錯誤', 'An unknown error occurred while loading the page'],
  ['發生未知錯誤，請重試', 'An unknown error occurred, please retry'],
  ['伺服器連接中斷，操作可能耗時過長。請稍後重試。', 'Server connection interrupted, operation may be taking too long. Please try again later.'],
  ['無法連接伺服器，可能是網絡中斷或伺服器超時。請檢查網絡後重試。', 'Cannot connect to server, possibly network down or server timeout. Please check your network and retry.'],
  ['請求超時，伺服器處理時間過長。請稍後重試。', 'Request timed out, server processing took too long. Please try again later.'],
  ['網路連線異常，請檢查您的網路', 'Network connection error, please check your network'],
  ['服務暫時無法使用，請稍後再試', 'Service temporarily unavailable, please try again later'],
  ['請求過於頻繁，請稍後再試', 'Too many requests, please try again later'],
  ['無法解析 JSON，使用默認', 'Cannot parse JSON, use default'],
  ['連接到本地 clawdbot WebSocket Gateway，執行瀏覽器自動化', 'Connect to local clawdbot WebSocket Gateway for browser automation'],
  ['自動清理過期任務（超過 5 分鐘的已完成任務）', 'Auto-clean expired tasks (completed tasks older than 5 minutes)'],
  ['任務進行中時，每 5 秒刷新一次', 'When task is in progress, refresh every 5 seconds'],
  ['延遲 reset isDragging，讓 onClick 可以判斷', 'Delay reset isDragging, let onClick decide'],
  ['使用後端代理下載圖片（繞過 CORS）', 'Download images via backend proxy (bypass CORS)'],
  ['使用原生 img 標籤，因為 blob URL 不支持', 'Use native img tag, since blob URL is not supported'],
  ['注意：這不是完美的安全方案，最佳實踐是使用', 'Note: This is not a perfect security solution, best practice is to use'],
  ['大於 10 商品將使用後端數步處理，頁面需要數', 'More than 10 products will use backend batch processing, page needs'],
  ['壓縮圖片的目標大小（8MB，留一些容量給後端）', 'Target size for image compression (8MB, leave some capacity for backend)'],
  ['逐步降低質量直到達到目標大小', 'Gradually reduce quality until target size is reached'],
  ['大量圖片一次 HTTP 上傳會超時', 'Uploading many images in one HTTP request will time out'],
  ['生產環境需要配置 FIRECRAWL_API_KEY 環境變量', 'Production environment requires FIRECRAWL_API_KEY env variable'],
  ['環境變量自動選擇合適的爬蟲服務，無需手動配置。', 'Env vars auto-select the appropriate scraper service, no manual config needed.'],
  ['幫助你及時掌握競爭動態，避免定價失誤造成的損失', 'Help you stay on top of competitive dynamics, avoid losses from pricing mistakes'],
  ['根據當前環境自動選擇爬蟲配置', 'Auto-select scraper config based on current environment'],
  ['只允許爬取 HKTVmall 官方域名', 'Only allow scraping HKTVmall official domains'],
  ['未登入，返回空（auth-provider 會處理跳轉到 login）', 'Not logged in, return empty (auth-provider handles redirect to login)'],
  ['已登入用戶顯示完整佈局（Future Tech 風格）', 'Logged in users see full layout (Future Tech style)'],
  ['不需要顯示 Sidebar 的公共頁面', 'Public pages that do not need Sidebar'],
  ['如果是公共頁面，直接渲染', 'If public page, render directly'],
  ['非公共頁面：等待認證檢查完成', 'Non-public pages: wait for auth check to complete'],
  ['任務不存在（DB 已持久化，僅過期或被刪前會 404）', 'Task not found (persisted in DB, only expired or deleted tasks return 404)'],
  ['全局快捷鍵啟用器（需要在 Provider 內部使用）', 'Global keyboard shortcuts enabler (must be used inside Provider)'],
  ['多語言內容（key = language code）', 'Multilingual content (key = language code)'],
  ['伺服器端渲染時不顯示動畫，避免 hydration 錯誤', 'Do not show animations during SSR to avoid hydration errors'],
  ['豐富動畫的 React 組件，打造沉浸式科技風格', 'Rich animated React components for immersive tech aesthetic'],
  ['超過 10 時顯示計數摘要，只渲染前 10 頁以避免 DOM 爆炸', 'Show count summary when >10, only render first 10 pages to avoid DOM bloat'],
  ['使用 Canvas 壓縮圖片', 'Compress images using Canvas'],
  ['如果圖片很大，先縮小尺寸', 'If image is large, reduce dimensions first'],
  ['已達最大上傳數量', 'Maximum upload count reached'],
  ['拖放圖片至此，或點擊選擇文件', 'Drag and drop images here, or click to select files'],
  ['顯示的任務：正在運行 + 等待中 + 最近完成的', 'Displayed tasks: running + pending + recently completed'],
  ['右下角常駐 Chatbot 按鍵 + 迷你聊天視窗', 'Persistent chatbot button + mini chat window in bottom right'],
  ['點擊右上角「添加商品」開始監測', 'Click "Add Product" in top right to start monitoring'],
  ['建議：爬取競品平台商品（長時間操作，分鐘超時）', 'Suggestion: Scrape competitor platform products (long operation, may time out)'],
  ['使用 Firecrawl 爬取頁面', 'Use Firecrawl to scrape page'],
  ['請確認 clawdbot 已啟動', 'Please confirm clawdbot is running'],
  ['檢查 Clawdbot 健康狀態', 'Check Clawdbot health status'],
  ['檢查 Clawdbot WebSocket 連接', 'Check Clawdbot WebSocket connection'],
  ['初始化 Clawdbot 連接器', 'Initialize Clawdbot connector'],
  ['初始化 Firecrawl 連接器', 'Initialize Firecrawl connector'],
  ['測試混合架構的自動切換功能', 'Test hybrid architecture auto-switch'],
  ['解析 features（逗號分隔轉數組，但要處理中文逗號）', 'Parse features (comma-separated to array, handle Chinese commas)'],
  ['前端需要使用 window.open 或 <a> 標籤觸發', 'Frontend needs window.open or <a> tag to trigger'],
  ['簡單內存緩存（注意：多實例部署時需要使用 Redis）', 'Simple memory cache (note: multi-instance deployments need Redis)'],
  ['每分鐘最大請求數', 'Max requests per minute'],
  ['請求超時時間（秒）', 'Request timeout (seconds)'],
  ['連續重試上限：防止無限循環', 'Consecutive retry limit: prevent infinite loops'],
  ['隨機延遲，避免觸發速率限制', 'Random delay to avoid triggering rate limits'],
  ['速率限制：每分鐘最大', 'Rate limit: max per minute'],
  ['最後一次嘗試，直接拋出錯誤', 'Last attempt, throw error directly'],
  ['轉換 Firecrawl 數據格式為統一格式', 'Convert Firecrawl data format to unified format'],
  ['地址檢驗（防止直接使用 IP 繞過域名檢查）', 'Address validation (prevent IP bypass of domain check)'],
  ['只允許 HTTPS 協議', 'Only allow HTTPS protocol'],
  ['檢查 URL 是否為 HKTVmall 搜索頁面', 'Check if URL is HKTVmall search page'],
  ['檢查 URL 是否為 HKTVmall 商品頁面', 'Check if URL is HKTVmall product page'],
  ['格式（SKU 號帶後綴如 H9423001_S_WNF-003A）', 'Format (SKU number with suffix e.g. H9423001_S_WNF-003A)'],
  ['格式，例如：.../p/H0340001 或', 'Format, e.g.: .../p/H0340001 or'],
  ['完整 URL，由呼叫方處理', 'Full URL, handled by caller'],
  ['保護 API 端點，防止未授權訪問', 'Protect API endpoints, prevent unauthorized access'],
  ['認證中間件（包裝 handler）', 'Auth middleware (wrapping handler)'],
  ['驗證 API Key 是否有效', 'Validate API Key'],
  ['驗證 API Key 格式', 'Validate API Key format'],
  ['獲取 API Key 的遮蔽版本（用於日誌）', 'Get masked API Key version (for logging)'],
  ['只顯示前 3 和後 4 字符', 'Only show first 3 and last 4 characters'],
  ['長度超過限制（最大 2048 字符）', 'Length exceeds limit (max 2048 characters)'],
  ['名稱或分類、HKTVmall URL 必須包含', 'Name or category, HKTVmall URL must contain'],
  ['安全使用 API Key 的工具函數', 'Utility functions for secure API Key usage'],
  ['詳細錯誤信息（FastAPI 標準格式）', 'Detailed error info (FastAPI standard format)'],
  ['智能爬取（使用緩存 + 增量更新）', 'Smart scraping (using cache + incremental updates)'],
  ['預覽爬取（不保存，需要審核）', 'Preview scraping (not saved, requires review)'],
  ['智能爬取 mutation（優化版，節省 API 配額）', 'Smart scraping mutation (optimized, saves API quota)'],
  ['智能爬取相關類型', 'Smart scraping related types'],
  ['智能爬取結果通知', 'Smart scraping result notification'],
  ['智能爬取狀態', 'Smart scraping status'],
  ['智能爬取失敗', 'Smart scraping failed'],
  ['快速爬取單個頁面', 'Quick scrape single page'],
  ['快速爬取 HKTVmall 商品', 'Quick scrape HKTVmall products'],
  ['快速爬取搜索排名', 'Quick scrape search rankings'],
  ['批量爬取商品', 'Batch scrape products'],
  ['批量爬取失敗', 'Batch scrape failed'],
  ['頁面爬取長連接', 'Page scraping long connection'],
  ['核心爬取方法', 'Core scraping method'],
  ['啟動管線後台任務（返回 task_id）', 'Start pipeline background task (returns task_id)'],
  ['導入商品頁面 URL，自動提取商品資訊', 'Import product page URL, auto-extract product info'],
  ['匹配：AI 配對自家商品與競品（5 分鐘超時）', 'Matching: AI pairs own products with competitors (5 min timeout)'],
  ['生成多語言內容（文案 + SEO + GEO）', 'Generate multilingual content (copy + SEO + GEO)'],
  ['一次 AI 調用生成多語言完整內容包：文案', 'One AI call generates multilingual complete content pack: copy'],
  ['打分：自動分類歸類（3 分鐘超時）', 'Scoring: auto-categorize (3 min timeout)'],
  ['獲取爬取中的即時耗時（秒）', 'Get real-time scraping elapsed time (seconds)'],
  ['當前正在處理的項目（脈搏動畫）', 'Currently processing item (pulse animation)'],
  ['當前正在處理的項目名稱', 'Currently processing item name'],
  ['路由變化時關閉移動端菜單', 'Close mobile menu on route change'],
  ['文件至少需要包含表頭和一行數據', 'File must contain at least a header and one data row'],
  ['請按照模板格式填寫商品資訊', 'Please fill in product info following the template format'],
  ['請上傳 CSV 或 Excel 文件', 'Please upload a CSV or Excel file'],
  ['請上傳 CSV 或 TXT 文件', 'Please upload a CSV or TXT file'],
  ['每行包含一個商品，使用逗號或 Tab 分隔', 'One product per line, separated by comma or Tab'],
  ['每行一個 URL，可選名稱和分類', 'One URL per line, optional name and category'],
  ['導入/更新商品 / 更新已有商品', 'Import new / update existing products'],
  ['文件批量添加監測商品，支持一次導入多商品', 'Bulk add monitored products via file, supports importing multiple products at once'],
  ['可用語言列表（name 從 i18n 字典讀取）', 'Available languages list (name read from i18n dictionary)'],
  ['過濾掉有鍵的項目，傳遞給父組件', 'Filter out keyed items, pass to parent component'],
  ['檢查菜單中是否有當前頁面', 'Check if current page exists in menu'],
  ['帶有動畫計數器和獨態指示的指標展示', 'Metrics display with animated counters and status indicators'],
  ['帶有動態克光效和手描線的玻璃', 'Glass effect with dynamic glow and hand-drawn lines'],
  ['底部導航欄 帶有動態克光效和手描線的玻璃', 'Bottom nav bar with dynamic glow and hand-drawn lines'],
  ['深色系背景，減少視覺疲勞', 'Dark background, reduces visual fatigue'],
  ['玻璃擬態效果，增加層次感', 'Glassmorphism effect, adds depth'],
  ['脈搏態勢指示，傳遞即時性', 'Pulse status indicator, conveys real-time updates'],
  ['暗色專業版', 'Dark professional edition'],
  ['底部進度條效果', 'Bottom progress bar effect'],
  ['未來科技感資訊欄 - 深色專業版', 'Futuristic info bar - dark professional edition'],
  ['頂部導航欄', 'Top navigation bar'],
  ['底部導航欄', 'Bottom navigation bar'],
  ['手動 pointer event，放手即停，零慣性', 'Manual pointer event, stops on release, zero inertia'],
  ['移動超過 5px 先算拖曳（避免誤觸）', 'Treat as drag after moving >5px (avoid accidental clicks)'],
  ['使用 useEffect 監聽數據變化', 'Use useEffect to watch data changes'],
  ['當圖片列表變化時，預加載所有縮圖名', 'When image list changes, preload all thumbnail names'],
  ['同頁面 key 在遷移時逐步追加', 'Same-page keys are added incrementally during migration'],
  ['生成頁籤（最多保留 10 頁籤 URL，避免大量圖片時記憶體高消費）', 'Generate tabs (max 10 tab URLs, avoid high memory usage with many images)'],
  ['點擊左側列表中的商品', 'Click a product in the left list'],
  ['查看詳細價格歷史與分析', 'View detailed price history and analysis'],
  ['目前沒有需要審批的改價提案。點擊上方「調整 AI 分析」按鈕生成新的提案。', 'No pricing proposals awaiting approval. Click "AI Analysis" button above to generate new proposals.'],
  ['請確認以下改價提案，批准後將自動更新 HKTVmall 價格。', 'Please confirm the following pricing proposals. Once approved, HKTVmall prices will be automatically updated.'],
  ['冇符合條件嘅商品', 'No products matching the criteria'],
  ['冇符合條件嘅商戶', 'No merchants matching the criteria'],
  ['未有商品比較數據', 'No product comparison data yet'],
  ['未有商戶數據', 'No merchant data yet'],
  ['無法載入商品列表，請稍後再試。', 'Unable to load product list, please try again later.'],
  ['展示 GoGoJap 為用戶創造的價值', 'Showcase the value GoGoJap creates for users'],
  ['本週為 GoGoJap 幫你節省造的總金額值', 'Total savings GoGoJap helped you achieve this week'],
  ['根據 period 計算趨勢天數', 'Calculate trend days based on period'],
  ['獲取有價格歷史的產品列表（供下拉選擇）', 'Get product list with price history (for dropdown selection)'],
  ['獲取有價格歷史的產品', 'Get products with price history'],
  ['輸入優化指令，例如：「加強限時優惠的緊迫感」「語氣更活潑」', 'Enter optimization instructions, e.g. "Add urgency to limited-time offers" "Make tone more lively"'],
  ['請加入限時優惠的緊迫感，如「限時8折」「上新一分鐘售罄」等', 'Please add urgency to limited-time offers, e.g. "Limited 20% off" "Sold out in one minute"'],
  ['請將文案語調改得更輕鬆有趣，加入更多香港地道口語', 'Please make the copy tone more casual and fun, add more authentic Hong Kong slang'],
  ['請精簡文案，保留重點，去除冗餘', 'Please refine the copy, keep the key points, remove redundancy'],
  ['請加強產品的核心賣點描述，突出米芝蓮/五星酒店背景', 'Please enhance the core selling points description, highlight Michelin/five-star hotel background'],
  ['請用更地道的香港口語重寫，讓文案更貼近本地消費者', 'Please rewrite in more authentic Hong Kong colloquial, make copy closer to local consumers'],
  ['統一內容生成流水線頁面（支持多語言）', 'Unified content generation pipeline page (supports multilingual)'],
  ['內容生成歷史記錄頁面', 'Content Generation History Page'],
  ['設置第一語言為活躍語言', 'Set first language as active language'],
  ['輔助 Hook：模擬爬取進度', 'Helper Hook: simulate scraping progress'],
  ['檢查 API 服務是否可用', 'Check if API service is available'],
  ['載入骨架組件', 'Loading skeleton component'],
  ['載入中...', 'Loading...'],
  ['處理中...', 'Processing...'],
  ['未授權，清除 Token 並重定向到登入', 'Unauthorized, clear token and redirect to login'],
  ['用於 React Query 緩存管理。', 'For React Query cache management.'],
  ['生產環境應使用數據庫映射', 'Production should use database mapping'],
  ['語言名稱映射（從 i18n 字典讀取）', 'Language name mapping (from i18n dictionary)'],
  ['構建完整 URL（含查詢字串）', 'Build full URL (with query string)'],
  ['如果有輸入新的 API Key，使用新的配置', 'If new API Key is entered, use new config'],
  ['否則使用已保存的配置', 'Otherwise use saved config'],
  ['如果有輸入新 URL 則使用，否則讓後端用保存的', 'If new URL entered, use it; otherwise let backend use saved value'],
  ['都沒有，顯示錯誤', 'Neither provided, show error'],
  ['動態獲取的模型列表', 'Dynamically fetched model list'],
  ['從 API 動態獲取模型', 'Dynamically fetch models from API'],
  ['驗證 API Key 是否已配置', 'Verify if API Key is configured'],
  ['獲取 API Key 的遮蔽版本（用於顯示）', 'Get masked API Key (for display)'],
  ['不再存儲在配置對象中，僅從環境變量讀取', 'No longer stored in config object, only read from env vars'],
  ['配置信息輸出（安全版本）', 'Config info output (safe version)'],
  ['提供統一的 API，自動路由到 Clawdbot 或', 'Provide unified API, auto-route to Clawdbot or'],
  ['抓取任務佇列組件', 'Scrape task queue component'],
  ['創建音頻元素', 'Create audio element'],
  ['訊息時間格式化', 'Message time formatting'],
  ['時間戳和操作按鈕', 'Timestamp and action buttons'],
  ['鍵盤快捷鍵提示 - 只在桌面顯示', 'Keyboard shortcut hints - desktop only'],
  ['計算是否為最後一個有效的 AI 訊息（用於顯示 follow-up）', 'Check if this is the last valid AI message (for showing follow-ups)'],
  ['Follow-up 建議 + 重新生成 - 只顯示在最後一個 AI 訊息', 'Follow-up suggestions + regenerate - only shown on last AI message'],
  ['找到最後一個用戶訊息', 'Find last user message'],
  ['移除最後一個 AI 回覆', 'Remove last AI reply'],
  ['添加 thinking 狀態', 'Add thinking state'],
  ['重新生成按鈕', 'Regenerate button'],
  ['Follow-up 建議按鈕', 'Follow-up suggestion buttons'],
  ['滾動到底部按鈕', 'Scroll to bottom button'],
  ['自動發送', 'Auto-send'],
  ['聲音提醒', 'Sound notification'],
  ['獲取建議', 'Get suggestions'],
  ['獲取歷史對話', 'Get conversation history'],
  ['加載歷史對話', 'Load conversation history'],
  ['發送訊息', 'Send message'],
  ['播放音效', 'Play sound effect'],
  ['發送澄清回應', 'Send clarification response'],
  ['鍵盤快捷鍵', 'Keyboard shortcuts'],
  ['新對話', 'New conversation'],
  ['聚焦輸入框', 'Focus input field'],
  ['取消焦點', 'Cancel focus'],
  ['滾動檢測', 'Scroll detection'],
  ['自動聚焦輸入框', 'Auto-focus input field'],
  ['Agent 圖標映射', 'Agent icon mapping'],
  ['狀態標籤', 'Status label'],
  ['訂閱的事件', 'Subscribed events'],
  ['擴展信息', 'Extended info'],
  ['類型定義', 'Type definitions'],
  ['主頁面', 'Main page'],
  ['數據摘要類型', 'Data summary type'],
  ['從數據庫加載數據', 'Load data from database'],
  ['並行獲取多數據源', 'Fetch multiple data sources in parallel'],
  ['獲取競品產品（取前3個競爭對手的產品）', 'Get competitor products (top 3 competitors)'],
  ['忽略單個競爭對手的錯誤', 'Ignore individual competitor errors'],
  ['組織數據結構', 'Organize data structure'],
  ['設置摘要數據供 UI 顯示', 'Set summary data for UI display'],
  ['未加載數據時顯示加載按鈕', 'Show load button when data not loaded'],
  ['已加載數據時顯示摘要', 'Show summary when data loaded'],
  ['統計數據網格', 'Statistics data grid'],
  ['產品樣本 - 手機隱藏', 'Product samples - hidden on mobile'],
  ['競品樣本 - 手機隱藏', 'Competitor samples - hidden on mobile'],
  ['重新加載按鈕', 'Reload button'],
  ['分析按鈕', 'Analysis button'],
  ['獲取警報數據', 'Fetch alert data'],
  ['標記已讀', 'Mark as read'],
  ['全部標記已讀', 'Mark all as read'],
  ['過濾和搜索', 'Filter and search'],
  ['按類型過濾', 'Filter by type'],
  ['搜索過濾', 'Search filter'],
  ['統計數據', 'Statistics'],
  ['批量操作', 'Batch operations'],
  ['骨架屏', 'Skeleton'],
  ['標題骨架屏', 'Title skeleton'],
  ['標題骨架', 'Title skeleton'],
  ['統計卡片骨架屏', 'Statistics card skeleton'],
  ['統計卡片骨架', 'Statistics card skeleton'],
  ['工具欄骨架屏', 'Toolbar skeleton'],
  ['列表骨架屏', 'List skeleton'],
  ['頁面標題', 'Page title'],
  ['工具欄', 'Toolbar'],
  ['搜索框', 'Search box'],
  ['過濾器', 'Filters'],
  ['警報列表', 'Alert list'],
  ['列表頭部', 'List header'],
  ['子組件', 'Sub-components'],
  ['可點擊的指標卡片包裝器', 'Clickable metric card wrapper'],
  ['選擇框', 'Checkbox'],
  ['價格變動', 'Price change'],
  ['操作按鈕', 'Action buttons'],
  ['內容 — 垂直排列', 'Content — vertical layout'],
  ['第一行：Badge + 未讀', 'Row 1: Badge + unread'],
  ['第二行：產品名', 'Row 2: Product name'],
  ['第三行：商戶名', 'Row 3: Merchant name'],
  ['第四行：價格 + 時間', 'Row 4: Price + time'],
  ['手機版操作按鈕', 'Mobile action buttons'],
  ['手機版卡片骨架', 'Mobile card skeleton'],
  ['桌面版表格骨架', 'Desktop table skeleton'],
  ['手機版卡片視圖', 'Mobile card view'],
  ['桌面版類別表格', 'Desktop category table'],
  ['錯誤提示', 'Error hint'],
  ['預覽審核界面', 'Preview review interface'],
  ['預覽標題', 'Preview title'],
  ['預覽商品列表', 'Preview product list'],
  ['預覽爬取 mutation', 'Preview scraping mutation'],
  ['預覽全選/取消全選', 'Preview select all/deselect all'],
  ['取消預覽', 'Cancel preview'],
  ['默認全選', 'Default select all'],
  ['圖表骨架屏', 'Chart skeleton'],
  ['圖表區域', 'Chart area'],
  ['價格分佈', 'Price distribution'],
  ['品牌比較', 'Brand comparison'],
  ['最優惠商品', 'Best deals'],
  ['商品價格歷史', 'Product price history'],
  ['商品列表', 'Product list'],
  ['智能爬取狀態', 'Smart scraping status'],
  ['切換商品選擇', 'Toggle product selection'],
  ['切換預覽商品選擇', 'Toggle preview product selection'],
  ['刪除單個商品', 'Delete single product'],
  ['批量刪除', 'Batch delete'],
  ['頂部骨架', 'Top skeleton'],
  ['主內容骨架', 'Main content skeleton'],
  ['頂部導航與標題', 'Top navigation and title'],
  ['返回競品列表', 'Back to competitors list'],
  ['統計卡片 - 使用', 'Statistics cards - using'],
  ['主要內容區域', 'Main content area'],
  ['左側：商品列表', 'Left: Product list'],
  ['搜索和過濾欄', 'Search and filter bar'],
  ['庫存過濾', 'Stock filter'],
  ['搜索商品名稱、分類...', 'Search product name, category...'],
  ['排序和過濾', 'Sort and filter'],
  ['分頁和搜索', 'Pagination and search'],
  ['事件處理', 'Event handlers'],
  ['批量導入處理', 'Bulk import handler'],
  ['數據查詢', 'Data queries'],
  ['渲染', 'Rendering'],
  ['加載狀態 - 使用', 'Loading state - using'],
  ['加載狀態', 'Loading state'],
  ['載入狀態', 'Loading state'],
  ['登入頁面 - Future Tech 設計', 'Login page - Future Tech design'],
  ['開發模式測試帳號', 'Development mode test account'],
  ['檢測是否為開發環境', 'Detect if development environment'],
  ['開發模式快速登入', 'Development mode quick login'],
  ['背景效果', 'Background effects'],
  ['裝飾元素', 'Decorative elements'],
  ['登入卡片', 'Login card'],
  ['Logo 區域', 'Logo area'],
  ['登入表單', 'Login form'],
  ['分隔線', 'Divider'],
  ['Google 登入', 'Google login'],
  ['發生錯誤', 'An error occurred'],
  ['系統發生錯誤', 'A system error occurred'],
  ['重新載入', 'Reload'],
  ['營運系統', 'Operations System'],
  ['競爭監測與價格追踪儀表板', 'Competitive monitoring and price tracking dashboard'],
  ['支持 iPhone 瀏海屏幕', 'Support iPhone notch screens'],
  ['首頁 - Future Tech Design', 'Home - Future Tech Design'],
  ['計算統計數據', 'Calculate statistics'],
  ['今日數據', 'Today data'],
  ['背景數據流 - 手機隱藏', 'Background data stream - hidden on mobile'],
  ['這裡是簡單示例，生產環境需要使用', 'This is a simple example, production requires'],
  ['右側：價格歷史側邊欄 - 使用', 'Right: Price history sidebar - using'],
  ['左側：快速操作 + 競爭對手', 'Left: Quick actions + competitors'],
  ['對話列表組件 - 支持編輯模式和批量', 'Conversation list component - supports edit mode and batch'],
  ['快速操作組件 - 常用問題快捷入口', 'Quick actions component - common question shortcuts'],
  ['競品建議流程 Dialog（SSE 串流版）', 'Competitor suggestion flow dialog (SSE streaming)'],
  ['批量競品匹配 Dialog（可複用組件）', 'Batch competitor matching dialog (reusable component)'],
  ['批量競品匹配（SSE 串流版）', 'Batch competitor matching (SSE streaming)'],
  ['當前步驟即時進度（匹配階段的逐商品進度）', 'Current step real-time progress (per-product progress during matching)'],
  ['簡單 CSV 解析（不處理引號內的逗號）', 'Simple CSV parsing (does not handle commas in quotes)'],
  ['提案統計卡片組件', 'Proposal statistics card component'],
  ['描述 - 使用 min-h 而非固定 h，避免手機版內容壓縮', 'Description - use min-h instead of fixed h, avoid mobile content compression'],
  ['潛在節省金額 - 突出顯示', 'Potential savings - highlighted'],
  ['總結 KPI 卡片組件', 'Summary KPI card component'],
  ['基於警報長連接計算的估算值', 'Estimated value based on alert long-connection calculation'],
  ['價格趨勢 KPI 卡片組件', 'Price trend KPI card component'],
  ['自家產品線（實線，更粗更明顯）', 'Own product line (solid, thicker and more visible)'],
  ['每行一 URL，可選名稱和分類', 'One URL per line, optional name and category'],
  ['分類：魚類 / 貨品 / 蟹類', 'Category: Fish / Goods / Crabs'],
  ['計算 Level 1 直接匹配', 'Calculate Level 1 direct match'],
  ['計算 Level 2 相似匹配', 'Calculate Level 2 similar match'],
  ['計算 Level 3 同類匹配', 'Calculate Level 3 same-category match'],
  ['頂部：圖標 + 名稱 + 狀態', 'Top: Icon + name + status'],
  ['每 2 秒輪一次', 'Poll every 2 seconds'],
  ['請精簡文案，保留重點，去除冗餘', 'Please refine the copy, keep key points, remove redundancy'],
  ['選中所有過濾結果（不超過上限）', 'Select all filtered results (up to limit)'],
  ['手機版：全屏顯示，留出安全距離', 'Mobile: full screen display, leave safe area'],
  ['如果有附件，將附件信息加入訊息', 'If attachments present, add attachment info to message'],
  ['鍵盤快捷鍵對話框', 'Keyboard shortcuts dialog'],
  ['按 <KeyBadge>Esc</KeyBadge> 關閉此視窗', 'Press <KeyBadge>Esc</KeyBadge> to close this window'],
  ['進度指示器（進行中時顯示）', 'Progress indicator (shown when in progress)'],
  ['開始追蹤關鍵詞以查看排名', 'Start tracking keywords to see rankings'],
  ['排名從第 15 名下降至第 42 名', 'Ranking dropped from #15 to #42'],
  ['排名從第 8 名上升至第 3 名', 'Ranking improved from #8 to #3'],
  ['關鍵詞配置彈窗', 'Keyword config dialog'],
  ['模式切換（僅添加時顯示）', 'Mode toggle (shown only when adding)'],
  ['單個模式：關鍵詞輸入', 'Single mode: keyword input'],
  ['批量創建關鍵詞配置', 'Batch create keyword configurations'],
  ['獲取關鍵詞排名歷史', 'Get keyword ranking history'],
  ['獲取關鍵詞建議', 'Get keyword suggestions'],
  ['獲取關鍵詞配置', 'Get keyword config'],
  ['創建關鍵詞配置', 'Create keyword config'],
  ['爬取關鍵詞搜索引擎', 'Scrape keyword search engine'],
  ['獲取 SEO 儀表板數據', 'Get SEO dashboard data'],
  ['每5分鐘自動刷新', 'Auto-refresh every 5 minutes'],
  ['提供使用 mock 數據的選項', 'Provide option to use mock data'],
  ['使用 mock 數據或 API 數據', 'Use mock or API data'],
  ['處理 Dialog 關閉：執行中禁止', 'Handle dialog close: disabled during execution'],
  ['處理中，請勿關閉此視窗', 'Processing, please do not close this window'],
  ['已記錄已輸出過的日誌，避免重複', 'Track previously output logs, avoid duplicates'],
  ['輔助組件：迷你任務指示器', 'Helper component: mini task indicator'],
  ['每30秒檢查一次', 'Check every 30 seconds'],
  ['扁平化 key-value 結構', 'Flatten key-value structure'],
  ['判斷是否為取消錯誤', 'Determine if cancellation error'],
  ['建立可取消的請求', 'Create cancellable request'],
  ['建立下載連結', 'Create download link'],
  ['獲取當前用戶的圖片生成限制', 'Get current user image generation limits'],
  ['當前步驟的活動訊息（脈搏顯示）', 'Current step activity message (pulse display)'],
  ['紫色 - 自家產品（虛線）', 'Purple - own products (dashed)'],
  ['青色 - 競爭對手 1（虛線）', 'Cyan - Competitor 1 (dashed)'],
  ['橙色 - 競爭對手 2（虛線）', 'Orange - Competitor 2 (dashed)'],
  ['綠色 - 競爭對手 3（虛線）', 'Green - Competitor 3 (dashed)'],
  ['紫色 - 競爭對手 4（虛線）', 'Purple - Competitor 4 (dashed)'],
  ['每分鐘檢查一次', 'Check every minute'],
  ['但允許 Escape 鍵', 'But allow Escape key'],
  ['檢查多權限（全部滿足）', 'Check multiple permissions (all must be met)'],
  ['主要 API 客戶端提供', 'Main API client provider'],
  ['驗證是否為開發環境', 'Check if development environment'],
  ['獲取 ROI 趨勢數據', 'Get ROI trend data'],
  ['獲取定價影響分析', 'Get pricing impact analysis'],
  ['獲取 AI 改價影響分析', 'Get AI pricing impact analysis'],
  ['獲取競爭監測洞察', 'Get competitive monitoring insights'],
  ['結構化數據 API 類型', 'Structured data API types'],
  ['品牌知識 - 獲取產品相關知識', 'Brand knowledge - get product knowledge'],
  ['品牌知識 - AI 生成專案', 'Brand knowledge - AI generated project'],
  ['完整分析流程（兩 AI 串聯）', 'Complete analysis flow (two AI in series)'],
  ['生成 Marketing 策略', 'Generate marketing strategy'],
  ['獲取排行榜數據', 'Get leaderboard data'],
  ['找到目標 URL 的排名', 'Find target URL ranking'],
  ['錯誤狀態組件', 'Error state component'],
  ['空狀態組件', 'Empty state component'],
  ['主頁面組件', 'Main page component'],
  ['瀏覽器操作序列', 'Browser action sequence'],
  ['需要 WebSocket 連接', 'Requires WebSocket connection'],
  ['處理 WebSocket 訊息', 'Process WebSocket message'],
  ['重置計數器（每分鐘）', 'Reset counter (per minute)'],
  ['實現 Redis 或內存速率限制', 'Implement Redis or memory rate limit'],
  ['過期時間（秒），預設', 'Expiry time (seconds), default'],
  ['必須認證（默認 true）', 'Requires authentication (default true)'],
  ['邏輯驗證 - 防止目錄遍歷', 'Logic validation - prevent directory traversal'],
  ['加載後觸發所有圖片', 'Load and trigger all images'],
  ['設定第一語言為活躍語言', 'Set first language as active language'],
  ['頁面入場動畫，提升體驗', 'Page entrance animations, enhance experience'],
  ['標題骨架', 'Title skeleton'],
  ['如果聊天視窗關閉，設置未讀', 'If chat window closed, set unread'],
  ['也都好得戟嘅 chat box 入面嘅', 'Also works great in the chat box'],
  ['有乜可以幫到你？問我啦！', 'What can I help with? Ask me!'],
  ['完整聊天頁面', 'Full chat page'],
  ['訊息反饋 - 只顯示在 AI 回覆', 'Message feedback - shown only on AI replies'],
  ['重新生成 - 只顯示在最後一個 AI 訊息', 'Regenerate - shown only on last AI message'],
  ['登錄/登出 + Enter 換行', 'Login/logout + Enter for newline'],
  ['按下 · Shift+Enter 換行', 'Press · Shift+Enter for newline'],
  ['爬取完成時顯示', 'Show when scraping complete'],
  ['儲存 Token 到安全存儲', 'Save token to secure storage'],
  ['直接返回 data 部分', 'Return data part directly'],
  ['安全 Token 管理器', 'Secure Token Manager'],
  ['已從 localStorage 遷移', 'Migrated from localStorage'],
  ['內存中的 token 緩存（最安全）', 'In-memory token cache (most secure)'],
  ['客戶端才能後生成隨機值', 'Only generate random value on client side'],
  ['使用 base64 + 反轉字串', 'Use base64 + reverse string'],
  ['擴展 globalThis 類型以支持', 'Extend globalThis types to support'],
  ['在 Agent 頁面不顯示此資訊（避免重複）', 'Do not show this info on Agent page (avoid duplication)'],
  ['全局爬取指示器組件', 'Global scrape indicator component'],
  ['請求攔截器：自動添加認證', 'Request interceptor: auto-add authentication'],
  ['清除已完成任務', 'Clear completed tasks'],
  ['檢查任務是否正在運行', 'Check if task is running'],
  ['如果任務完成，刷新相關數據', 'If task completed, refresh related data'],
  ['輸入商品連接，系統將自動爬取價格和庫存信息。', 'Enter product link, the system will automatically scrape prices and inventory info.'],
  ['說明最大導入 100 個商品', 'Note: max 100 products per import'],
  ['瀑布流展示頁面', 'Waterfall gallery page'],
  ['季節性商品（使用現有商品數據）', 'Seasonal products (using existing product data)'],
  ['可選處理尚未匹配競品的商品', 'Optionally process products without competitor matches'],
  ['建議先執行 10 商品測試', 'Recommend testing with 10 products first'],
  ['配額偏低，建議使用智能爬取以節省消耗', 'Quota is low, recommend using smart scraping to save usage'],
  ['開始追蹤關鍵詞以查看排名', 'Start tracking keywords to view rankings'],
  ['數據 - 暫時只顯示 pending 數量', 'Data - currently only showing pending count'],
  ['完成所有更新步驟（保證「完成」日誌在「開始下一步」之前）', 'Complete all update steps (ensure "completed" log is before "start next step")'],
  ['如果有輸入新 URL 則使用，否則讓後端用保存的', 'If new URL entered, use it; otherwise let backend use saved'],
  ['確認 clawdbot 已啟動', 'Confirm clawdbot is running'],
  ['通過後端代理下載圖片（繞過 CORS）', 'Download images via backend proxy (bypass CORS)'],
  ['自定義文件驗證器（只檢查副檔名，不檢查大小，因為會自動壓縮）', 'Custom file validator (check extension only, not size, auto-compression)'],
  ['爬取失敗，請稍後重試', 'Scraping failed, please try again later'],
  ['成功保存', 'Successfully saved'],
  ['保存失敗，請稍後重試', 'Save failed, please try again later'],
  ['成功刪除', 'Successfully deleted'],
  ['刪除失敗', 'Delete failed'],
  ['爬取頁面', 'Scrape page'],
  ['當前環境的爬蟲配置（不包含 API Key）', 'Current env scraper config (excluding API Key)'],
  ['無法匹配搜索的商品選擇 AI 分析', 'Cannot match searched products for AI analysis'],
  ['即時進度（匹配階段的逐商品進度）', 'Real-time progress (per-product progress during matching)'],
  ['文件處理（包括壓縮大文件）', 'File processing (including large file compression)'],
  ['輸入圖片（自動分批，每批最大 10 張）', 'Input images (auto-batched, max 10 per batch)'],
  ['已選擇商品（商品選擇模式）', 'Selected products (product selection mode)'],
  ['瀕危告警長連接', 'Critical alert long connection'],
  ['將瀕危商品數據轉為告警格式', 'Convert critical product data to alert format'],
  ['只會處理尚未匹配競品的商品', 'Only process products without competitor matches'],
  ['即時進度條（匹配階段的逐商品進度）', 'Real-time progress bar (per-product progress during matching)'],
  ['耗時：running 時用 heartbeat 即時值', 'Duration: use heartbeat real-time value when running'],
  ['生產環境應使用數據庫對應', 'Production should use database mapping'],
  ['需要配置 FIRECRAWL_API_KEY 環境變量', 'Requires FIRECRAWL_API_KEY environment variable'],
  ['進度條：processing / done 時顯示', 'Progress bar: show when processing / done'],
  ['使用本地 Clawdbot 服務', 'Use local Clawdbot service'],
  ['使用雲端 Firecrawl 服務', 'Use cloud Firecrawl service'],
  ['結果使用現有商品數據過濾', 'Filter results using existing product data'],
  ['為搜索頁面', 'is a search page'],
  ['記錄已輸出過的日誌，避免重複', 'Track previously output logs to avoid duplicates'],
  ['惠康 屈臣氏', 'Wellcome Watsons'],
  ['例如：Watsons 屈臣氏', 'e.g. Watsons'],
  ['高威脅 · 價差 >20%', 'High Threat · Price gap >20%'],
  ['注意 · 價差 5-20%', 'Warning · Price gap 5-20%'],
  ['正常範圍', 'Normal range'],
  ['我哋最平 🏆', 'We are cheapest 🏆'],
  ['商戶 ·', 'merchants ·'],
  ['商品', 'products'],
  ['商戶', 'merchants'],
  ['建議', 'suggestions'],
  ['自家競品', 'Own competitors'],
  ['全部生鮮', 'All fresh food'],
  ['匯出 CSV', 'Export CSV'],
  ['匯出', 'Export'],
  ['刷新', 'Refresh'],
  ['有貨商品', 'In-stock products'],
  ['缺貨商品', 'Out-of-stock products'],
  ['價格上漲', 'Price increase'],
  ['價格下跌', 'Price decrease'],
  ['監測商品', 'Monitored products'],
  ['立即爬取', 'Scrape now'],
  ['添加商品', 'Add product'],
  ['有貨', 'In stock'],
  ['缺貨', 'Out of stock'],
  ['名稱', 'Name'],
  ['價格', 'Price'],
  ['價格變動', 'Price change'],
  ['更新時間', 'Update time'],
  ['已選', 'Selected'],
  ['取消選擇', 'Deselect'],
  ['訪問商品頁面', 'Visit product page'],
  ['訪問頁面', 'Visit page'],
  ['問其他嘢', 'Ask something else'],
  ['還有', 'And'],
  ['個錯誤...', 'more errors...'],
  ['件', 'items'],
  ['產品名', 'Product name'],
  ['商戶名', 'Merchant name'],
  ['圖標', 'Icon'],
  ['未讀', 'Unread'],
  ['發生', 'occurred'],
  ['頁面', 'page'],
  ['按鈕', 'button'],
  ['確認', 'Confirm'],
  ['否則', 'Otherwise'],
  ['是否', 'whether'],
  ['已經', 'already'],
  ['正在', 'currently'],
  ['設計', 'Design'],
  ['組件', 'Component'],
  ['狀態', 'State'],
  ['登入', 'Login'],
  ['圖片', 'Image'],
  ['後端', 'Backend'],
  ['前端', 'Frontend'],
  ['伺服器', 'Server'],
  ['瀏覽器', 'Browser'],
  ['數據', 'Data'],
  ['環境', 'Environment'],
  ['配置', 'Configuration'],
  ['模型', 'Model'],
  ['暫停', 'Pause'],
  ['繼續', 'Continue'],
  ['資訊', 'Information'],
  ['管理', 'Management'],
  ['系統', 'System'],
  ['產品', 'Product'],
  ['對手', 'Competitor'],
  ['顯示', 'Display'],
  ['隱藏', 'Hidden'],
  ['自動', 'Auto'],
  ['手動', 'Manual'],
  ['預設', 'Default'],
  ['目前', 'Currently'],
  ['成功', 'Success'],
  ['失敗', 'Failed'],
  ['完成', 'Complete'],
  ['錯誤', 'Error'],
  ['未知', 'Unknown'],
  ['測試', 'Test'],
  ['開發', 'Development'],
  ['密碼', 'Password'],
  ['帳號', 'Account'],
  ['使用者', 'User'],
  ['功能', 'Feature'],
  ['版本', 'Version'],
  ['更新', 'Update'],
  ['查詢', 'Query'],
  ['結果', 'Result'],
  ['記錄', 'Record'],
  ['歷史', 'History'],
  ['分析', 'Analysis'],
  ['報告', 'Report'],
  ['通知', 'Notification'],
  ['設定', 'Settings'],
  ['選擇', 'Select'],
  ['刪除', 'Delete'],
  ['新增', 'Add'],
  ['編輯', 'Edit'],
  ['保存', 'Save'],
  ['取消', 'Cancel'],
  ['關閉', 'Close'],
  ['返回', 'Back'],
  ['確定', 'OK'],
  ['提交', 'Submit'],
  ['搜尋', 'Search'],
  ['上傳', 'Upload'],
  ['下載', 'Download'],
  ['載入', 'Load'],
  ['排序', 'Sort'],
  ['篩選', 'Filter'],
  ['全部', 'All'],
  ['啟用', 'Enable'],
  ['停用', 'Disable'],
  ['支持', 'Support'],
  ['格式', 'Format'],
  ['類型', 'Type'],
  ['內容', 'Content'],
  ['標題', 'Title'],
  ['描述', 'Description'],
  ['圖表', 'Chart'],
  ['總計', 'Total'],
  ['數量', 'Quantity'],
  ['百分比', 'Percentage'],
  ['日期', 'Date'],
  ['時間', 'Time'],
  ['開始', 'Start'],
  ['結束', 'End'],
  ['重試', 'Retry'],
  ['分鐘', 'minutes'],
  ['小時', 'hours'],
  ['秒鐘', 'seconds'],
  ['文件', 'File'],
  ['圖片', 'Image'],
  ['視頻', 'Video'],
  ['音頻', 'Audio'],
  ['連接', 'Connection'],
  ['斷開', 'Disconnected'],
  ['等待', 'Waiting'],
  ['處理', 'Processing'],
  ['準備', 'Ready'],
  ['運行', 'Running'],
  ['暫停', 'Paused'],
  ['停止', 'Stopped'],
  ['加載', 'Loading'],
  ['儲存', 'Save'],
  ['導入', 'Import'],
  ['導出', 'Export'],
  ['創建', 'Create'],
  ['獲取', 'Fetch'],
  ['計算', 'Calculate'],
  ['檢查', 'Check'],
  ['驗證', 'Validate'],
  ['解析', 'Parse'],
  ['轉換', 'Convert'],
  ['生成', 'Generate'],
  ['初始化', 'Initialize'],
  ['設置', 'Set up'],
  ['清除', 'Clear'],
  ['清理', 'Clean up'],
  ['重置', 'Reset'],
  ['監測', 'Monitor'],
  ['追蹤', 'Track'],
  ['爬取', 'Scrape'],
  ['匹配', 'Match'],
  ['配對', 'Pair'],
  ['比較', 'Compare'],
  ['過濾', 'Filter'],
  ['排名', 'Ranking'],
  ['評分', 'Score'],
  ['優化', 'Optimize'],
  ['審核', 'Review'],
  ['批准', 'Approve'],
  ['拒絕', 'Reject'],
  ['提案', 'Proposal'],
  ['策略', 'Strategy'],
  ['趨勢', 'Trend'],
  ['洞察', 'Insight'],
  ['警報', 'Alert'],
  ['提醒', 'Reminder'],
  ['通知', 'Notification'],
  ['日誌', 'Log'],
  ['緩存', 'Cache'],
  ['配額', 'Quota'],
  ['權限', 'Permission'],
  ['角色', 'Role'],
  ['認證', 'Authentication'],
  ['授權', 'Authorization'],
  ['安全', 'Security'],
  ['加密', 'Encryption'],
  ['攻擊', 'Attack'],
  ['防止', 'Prevent'],
  ['允許', 'Allow'],
  ['禁止', 'Block'],
  ['攔截', 'Intercept'],
  ['響應', 'Response'],
  ['請求', 'Request'],
  ['回調', 'Callback'],
  ['列表', 'List'],
  ['詳情', 'Details'],
  ['卡片', 'Card'],
  ['表格', 'Table'],
  ['彈窗', 'Popup'],
  ['對話框', 'Dialog'],
  ['側邊欄', 'Sidebar'],
  ['導航', 'Navigation'],
  ['菜單', 'Menu'],
  ['搜索', 'Search'],
  ['操作', 'Operation'],
  ['區域', 'Area'],
  ['佈局', 'Layout'],
  ['樣式', 'Style'],
  ['主題', 'Theme'],
  ['動畫', 'Animation'],
  ['效果', 'Effect'],
  ['欄', 'Bar'],
  ['競品', 'Competitor'],
  ['定價', 'Pricing'],
  ['調價', 'Price adjustment'],
  ['改價', 'Price change'],
  ['利潤', 'Profit'],
  ['收入', 'Revenue'],
  ['成本', 'Cost'],
  ['損失', 'Loss'],
  ['節省', 'Savings'],
  ['評估', 'Evaluate'],
  ['決策', 'Decision'],
  ['範圍', 'Range'],
  ['閾值', 'Threshold'],
  ['觸發', 'Trigger'],
  ['超時', 'Timeout'],
  ['限制', 'Limit'],
  ['上限', 'Upper limit'],
  ['下限', 'Lower limit'],
  ['默認', 'Default'],
  ['選項', 'Option'],
  ['參數', 'Parameter'],
  ['變量', 'Variable'],
  ['常量', 'Constant'],
  ['接口', 'Interface'],
  ['方法', 'Method'],
  ['函數', 'Function'],
  ['物件', 'Object'],
  ['陣列', 'Array'],
  ['字串', 'String'],
  ['數字', 'Number'],
  ['布爾', 'Boolean'],
  ['空值', 'Null'],
  ['異步', 'Async'],
  ['同步', 'Sync'],
  ['回傳', 'Return'],
  ['拋出', 'Throw'],
  ['捕獲', 'Catch'],
  ['嘗試', 'Try'],
  ['遍歷', 'Iterate'],
  ['映射', 'Map'],
  ['過期', 'Expired'],
  ['有效', 'Valid'],
  ['無效', 'Invalid'],
  ['必須', 'Required'],
  ['可選', 'Optional'],
  ['忽略', 'Ignore'],
  ['跳過', 'Skip'],
  ['繼續', 'Continue'],
  ['中斷', 'Interrupt'],
  ['重新', 'Re-'],
  ['目標', 'Target'],
  ['來源', 'Source'],
  ['輸入', 'Input'],
  ['輸出', 'Output'],
  ['上傳', 'Upload'],
  ['下載', 'Download'],
  ['遷移', 'Migrate'],
  ['壓縮', 'Compress'],
  ['統一', 'Unified'],
  ['整合', 'Integrate'],
  ['擴展', 'Extend'],
  ['自定義', 'Custom'],
  ['提供', 'Provide'],
  ['包含', 'Include'],
  ['排除', 'Exclude'],
  ['避免', 'Avoid'],
  ['確保', 'Ensure'],
  ['需要', 'Need'],
];

let totalChanges = 0;
const changedFiles = [];
const fileDetails = {};

for (const filePath of files) {
  if (filePath.includes('zh-HK') || filePath.includes('_translate')) continue;
  
  let content = readFileSync(filePath, 'utf-8');
  const original = content;
  
  for (const [cn, en] of translations) {
    content = content.replaceAll(cn, en);
  }
  
  if (content !== original) {
    writeFileSync(filePath, content, 'utf-8');
    totalChanges++;
    const shortPath = filePath.replace(/.*?\\src\\/, 'src/');
    changedFiles.push(shortPath);
    console.log(`✅ ${shortPath}`);
  }
}

console.log(`\n========================================`);
console.log(`Changed ${totalChanges} files`);
console.log(`========================================\n`);

// Check remaining Chinese
try {
  const remaining = execSync(
    `powershell -Command "Get-ChildItem -Recurse -Include *.tsx,*.ts,*.jsx | Where-Object { $_.FullName -notmatch 'zh-HK' -and $_.FullName -notmatch '_translate' } | Select-String -Pattern '[\\u4e00-\\u9fff]' | Select-Object -ExpandProperty Path -Unique"`,
    { cwd: srcDir, encoding: 'utf-8' }
  ).trim().split('\n').filter(f => f.trim() && !f.includes('Active code page'));
  
  if (remaining.length > 0 && remaining[0]) {
    console.log(`⚠️  ${remaining.length} files still have Chinese:\n`);
    
    // Show remaining Chinese per file
    for (const f of remaining.slice(0, 10)) {
      if (!f.trim()) continue;
      try {
        const lines = execSync(
          `findstr /n /r "[一-龥]" "${f.trim()}"`,
          { encoding: 'utf-8', cwd: srcDir }
        ).trim().split('\n').slice(0, 5);
        console.log(`\n  ${f.trim().replace(/.*?\\src\\/, '')}:`);
        lines.forEach(l => console.log(`    ${l.trim()}`));
      } catch {}
    }
  } else {
    console.log('🎉 All Chinese text has been translated!');
  }
} catch(e) {
  console.log('Check complete (no remaining Chinese found or check failed)');
}
